=== lly2601391756/repo4/TeachersXML/src/main/resources/teachers.xsd
<?xml version="1.0"?>
<xsd:schema xmlns="http://www.chinasoft.cn/xml"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://www.chinasoft.cn/xml" elementFormDefault="qualified">
    <xsd:element name="teachers" type="teachersType"/>  <!-- 规定根标签名称students，类型studentsType -->
    <xsd:complexType name="teachersType">   <!--表示studentsType类型中包含student标签-->
        <xsd:sequence>      <!--student标签最少0个，最大：无穷 minOccurs:最小值 ，maxOccurs：最大值-->
            <xsd:element name="teacher" type="teacherType" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>
    <xsd:complexType name="teacherType">
        <xsd:sequence>
            <xsd:element name="name" type="xsd:string"/>
            <xsd:element name="gender" type="genderType" />
            <xsd:element name="salary" type="xsd:double" />
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:int" use="required"/>
    </xsd:complexType>
    <xsd:simpleType name="genderType">
        <xsd:restriction base="xsd:string">
            <xsd:enumeration value="male"/>     <!--枚举 表示值必须是male或female-->
            <xsd:enumeration value="female"/>
        </xsd:restriction>
    </xsd:simpleType>
</xsd:schema>

=== lly2601391756/repo4/TeachersXML/src/main/resources/teachers.xml
<?xml version="1.0" encoding="UTF-8" ?>
<!--
	1.填写xml文档的根元素
	2.引入xsi前缀.  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	3.引入xsd文件命名空间.  xsi:schemaLocation="http://www.chinasoft.cn/xml  student.xsd"
	4.为每一个xsd约束声明一个前缀,作为标识  xmlns="http://www.chinasoft.cn/xml"


 -->
<teachers  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xmlns="http://www.chinasoft.cn/xml"
            xsi:schemaLocation="http://www.chinasoft.cn/xml  teachers.xsd"
>
    <teacher id="1">
        <name>张三</name>
        <gender>female</gender>
        <salary>5000</salary>
    </teacher>

    <teacher id="2">
        <name>李四</name>
        <gender>male</gender>
        <salary>3000</salary>
    </teacher>

    <teacher id="3">
        <name>王五</name>
        <gender>male</gender>
        <salary>6000</salary>
    </teacher>
</teachers>
